name: template
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  gap:
  google_fonts: ^6.2.1
  go_router:
  adaptive_theme:
  bounce: ^1.0.2
  motion: ^2.0.1
  universal_io: ^2.2.2
  supabase_flutter: ^2.3.4
  envied: ^0.5.3
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  envied_generator: ^0.5.3
  build_runner: ^2.4.8
  mockito: ^5.4.4

flutter:
  uses-material-design: true